name:                raytracer
version:             0.1.0.0
github:              "karlfroldan/raytracer"
license:             None
author:              "Author name here"
maintainer:          "karlfroldan@gmail.com"
copyright:           "2022 Karl Frederick R. Roldan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/raytracer#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.4.0 && < 0.6.0.0
- mtl >= 2.2.2
- split >= 0.2.3
- lens >= 5
- linear >= 1.20.0

library:
  source-dirs: src

executables:
  raytracer:
    main:                Main.hs
    source-dirs:         app/Raytracer
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raytracer
  projectile:
    main:                Main.hs
    source-dirs:         app/Projectile
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raytracer
    - mtl >= 2.2.2
    - process >= 1.6.10
    - lens >= 5
    - linear >= 1.20.0

tests:
  raytracer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raytracer
    - hspec >= 2.8.5
    - HUnit >= 1.6.0.0